import json

notebook_path = '/home/voitanta/Github/LUMI_AIF_Template/content/03_notebook_example.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 1
nb['cells'][0]['source'] = [
    "# Chapter 2: Jupyter Notebooks\n",
    "\n",
    "This page is rendered directly from `content/03_notebook_example.ipynb`. Notebooks dropped into `content/` are automatically converted to pages on the fly, retaining standard page features like sidebar navigation and table of contents. The notebook itself remains the only source of truth.\n",
    "\n",
    "## Markdown cells\n",
    "\n",
    "Markdown cells support all standard template features like formatting, [links](/chapter1), tables, and callouts.\n",
    "\n",
    "> [!note] Callouts work too\n",
    "> This callout is rendered from a notebook markdown cell.\n",
    "\n",
    "## Code cells\n",
    "\n",
    "Code cells are converted into standard code blocks with syntax highlighting and a copy button:"
]

# Cell 3
nb['cells'][2]['source'] = [
    "Cell outputs are excluded by design. Pages display the code to be run, not saved execution results.\n",
    "\n",
    "## Configuration\n",
    "\n",
    "Notebooks do not require front matter.\n",
    "- **Title**: Derived from the notebook's first heading, falling back to the filename.\n",
    "- **Sidebar Order**: Determined by an optional leading number in the filename (e.g., `03_...`).\n",
    "\n",
    "To add custom front matter, insert a **Raw** cell at the very top of the notebook containing YAML:\n",
    "\n",
    "```yaml\n",
    "parent: \"Chapter 1: Getting Started with LUMI\"\n",
    "description: \"Running your first inference job.\"\n",
    "```\n",
    "\n",
    "## Images\n",
    "\n",
    "- **Pasted into markdown**: Stored natively in the `.ipynb` and rendered automatically.\n",
    "- **External files**: e.g., `![caption](./images/plot.png)`. Move image files to `public/assets/`. The template resolves the path using just the filename, ignoring the directory path in the markdown link.\n",
    "\n",
    "![The LUMI AI Factory logo](./images/lumi-ai-factory-logo.png)\n",
    "\n",
    "Plots generated by code cells are omitted as outputs. To display them, save the plot to a file, place it in `public/assets/`, and link to it manually."
]

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
    f.write('\n')

print("Notebook updated successfully.")
